spring:
  datasource:
        driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
        url: jdbc:h2:mem:testdb  # H2 접속 정보
        username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
        password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true


  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 500MB




server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript, application/json, application/zip, application/octet-stream, application/pdf, video/mp4
  port: 60000
